### ISSUE TITLE
operazioni

### ISSUE THREAD

**Issue by FabioZTessitore** [LeonardoRiselli/helloworld_c#1]
in attesa

**Comment by LeonardoRiselli** [comment]
caricato le operazioni ora faccio il secondo

**Comment by LeonardoRiselli** [comment]
il secondo ve lo defo far controllare domani che mi da degli errori che non capisco

**Comment by FabioZTessitore** [comment]
Le operazioni. Plurale

**Comment by FabioZTessitore** [comment]
aggiusta gitignore

**Comment by FabioZTessitore** [comment]
se non aggiusti gitignore non vai avanti
