### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [LeonardoRiselli/helloworld_c#2]
il raggio deve essere intero.
i risultati invece sono double, quindi attento alla stampa

**Comment by LeonardoRiselli** [comment]
Ok lo controllo

**Comment by LeonardoRiselli** [comment]
fatto prof ho chiesto un aiuto al signor carlo e mi ha consigliato di mettere %.0f dicendomi a che serviva spero vada bene.

**Comment by FabioZTessitore** [comment]
non hai caricato l'ultima versione

**Comment by LeonardoRiselli** [comment]
Scusate prof pensavo di avervela caricata appena posso la invio ora sto per
strada andando a scuola.

Il 22 feb 2017 22:35, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LeonardoRiselli** [comment]
fatto caricata
