### ISSUE TITLE
maggiore2

### ISSUE THREAD

**Issue by FabioZTessitore** [LeonardoRiselli/helloworld_c#3]
prova a risolverlo usando solo una if

**Comment by LeonardoRiselli** [comment]
A giusto con l'else

**Comment by LeonardoRiselli** [comment]
fatto prof ho anche aggiornato il .gitignore poi domani vi mando il prossimo

**Comment by FabioZTessitore** [comment]
niente else, solo un if e niente altro

**Comment by LeonardoRiselli** [comment]
Scusate prof ma come faccio senza else se non lo metto come faccio a dire se b>a fai questo?

**Comment by FabioZTessitore** [comment]
devi trovare un'altra soluzione

**Comment by LeonardoRiselli** [comment]
Ora ci penso

Il 1 mar 2017 3:46 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:
